# Generated by Django 3.2.5 on 2021-11-24 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_auto_20211116_1102'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('order', models.IntegerField(verbose_name='Ordem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'file'), ('t', 'text')], max_length=1, verbose_name='Tipo de submissão')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Descrição')),
                ('min_objects', models.IntegerField(null=True, verbose_name='Mínimo de objetos')),
                ('max_objects', models.IntegerField(null=True, verbose_name='Máximo de objetos')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Descrição')),
                ('recurrence', models.CharField(choices=[('d', 'day'), ('w', 'week'), ('m', 'month')], max_length=1, null=True, verbose_name='Recorrência')),
                ('recurrence_index', models.IntegerField(null=True, verbose_name='Índice do dia')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category', verbose_name='Categoria')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.group', verbose_name='Grupo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.submission', verbose_name='Submissão')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(verbose_name='Prazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('is_concluded', models.BooleanField(null=True, verbose_name='Status de conclusão')),
                ('concluded_at', models.DateTimeField(verbose_name='Data de conclusão')),
                ('obs', models.CharField(max_length=500, null=True, verbose_name='Observação')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='tasks/response', verbose_name='Arquivo de upload')),
                ('text', models.CharField(max_length=500, null=True, verbose_name='Texto de resposta')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usertask', verbose_name='Tarefa de usuário')),
            ],
        ),
    ]
