# Generated by Django 3.2.5 on 2021-11-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20211116_1102'),
        ('tasks', '0002_auto_20211124_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.IntegerField(default=None, verbose_name='Ordem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Loja'),
            preserve_default=False,
        ),
    ]
