# Generated by Django 3.2.5 on 2021-11-25 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_category_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='advance_days',
            field=models.IntegerField(null=True, verbose_name='Antecedência de lançamento'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertask',
            name='concluded_at',
            field=models.DateTimeField(null=True, verbose_name='Data de conclusão'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='obs',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PeriodicRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(blank=True, max_length=500, verbose_name='Observação')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Tarefa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
