# Generated by Django 3.2.5 on 2021-11-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_shortcut_order'),
        ('tasks', '0005_auto_20211125_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.RemoveField(
            model_name='group',
            name='store',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
