# Generated by Django 3.2.5 on 2021-11-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20211130_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Tarefa'),
            preserve_default=False,
        ),
    ]
