# Generated by Django 3.2.5 on 2021-11-30 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_auto_20211130_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicrelation',
            options={'verbose_name': 'Relação Periódica', 'verbose_name_plural': 'Relações Periódicas'},
        ),
        migrations.AlterField(
            model_name='periodicrelation',
            name='obs',
            field=models.CharField(blank=True, help_text='Esse texto é exibido nas instâncias de tarefas criadas', max_length=500, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='periodicrelation',
            name='task',
            field=models.ForeignKey(help_text='Escolha uma tarefa periódica', on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_objects',
            field=models.IntegerField(blank=True, help_text='Deixe em branco para submissão simples; max de arquivos para submissão file e max de caracteres para submissão text', null=True, verbose_name='Máximo de objetos'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='min_objects',
            field=models.IntegerField(blank=True, help_text='Deixe em branco para submissão simples; min de arquivos para submissão file e min de caracteres para submissão text', null=True, verbose_name='Mínimo de objetos'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='advance_days',
            field=models.IntegerField(help_text='0 para lançamento no mesmo dia da entrega, 1 para lancamento no dia anterior, etc.', null=True, verbose_name='Qtd. de dias de antecedência para lançamento'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence_index',
            field=models.IntegerField(blank=True, help_text='Deixe em branco para recorrência diária; Recorrência Semanal: preencher com 0 (segunda) até 6(domingo); Recorrência Mensal: preencher com 1 até 31', null=True, verbose_name='Índice do dia'),
        ),
        migrations.AlterUniqueTogether(
            name='periodicrelation',
            unique_together={('task', 'user')},
        ),
    ]
