# Generated by Django 3.2.5 on 2021-12-01 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20211130_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.submission', verbose_name='Submissão'),
        ),
    ]
