# Generated by Django 3.2.5 on 2022-02-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
