# Generated by Django 3.2.5 on 2022-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_task_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicrelation',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
