# Generated by Django 3.2.5 on 2022-03-22 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_periodicrelation_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicrelation',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
