# Generated by Django 3.2.5 on 2022-07-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_usertask_ifood_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
