# Generated by Django 3.2.5 on 2022-06-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_usertask_ifood_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Tempo sugerido'),
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_choice', models.CharField(choices=[('p', 'pessoal'), ('t', 'transito'), ('c', 'clima'), ('o', 'outros')], max_length=1, null=True, verbose_name='Motivos')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Descrição')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usertask', verbose_name='Tarefa de usuário')),
            ],
        ),
    ]
