# Generated by Django 3.2.5 on 2022-06-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_auto_20220609_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', 'pessoal'), ('t', 'transito'), ('c', 'clima'), ('a', 'automático'), ('o', 'outros')], max_length=1, verbose_name='Motivos')),
            ],
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.reasonchoice', verbose_name='Motivos'),
            preserve_default=False,
        ),
    ]
