# Generated by Django 3.2.5 on 2022-06-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20220609_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasonchoice',
            name='description',
            field=models.CharField(max_length=80, null=True, verbose_name='Descrição'),
        ),
    ]
