# Generated by Django 3.2.5 on 2022-06-10 18:35

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_reasonchoice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Dado')),
                ('data', models.FileField(upload_to=tasks.models.get_upload_supporting, verbose_name='Dado')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='supporting_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.supporting', verbose_name='Dados sugeridos'),
        ),
    ]
