# Generated by Django 3.2.5 on 2022-06-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20220610_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='supporting_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.supporting', verbose_name='Dados sugeridos'),
        ),
    ]
