# Generated by Django 3.2.5 on 2022-06-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_alter_task_supporting_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='supporting_data',
        ),
        migrations.AddField(
            model_name='supporting',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Tarefa'),
            preserve_default=False,
        ),
    ]
