# Generated by Django 3.2.5 on 2022-06-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_auto_20220613_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporting',
            name='type',
        ),
    ]
