# Generated by Django 3.2.5 on 2022-06-14 13:48

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_remove_supporting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporting',
            name='link',
            field=models.URLField(null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='supporting',
            name='type',
            field=models.CharField(choices=[('f', 'file'), ('l', 'link'), ('v', 'video')], default=1, max_length=1, verbose_name='Tipo de apoio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supporting',
            name='data',
            field=models.FileField(null=True, upload_to=tasks.models.get_upload_supporting, verbose_name='Dado'),
        ),
    ]
