# Generated by Django 3.2.5 on 2022-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_alter_supporting_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporting',
            name='type',
            field=models.CharField(choices=[('f', 'file'), ('l', 'link'), ('v', 'video'), ('i', 'internal')], max_length=1, verbose_name='Tipo de apoio'),
        ),
    ]
