# Generated by Django 3.2.5 on 2022-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_alter_supporting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supporting_changed',
            field=models.BooleanField(default=False, verbose_name='Mudanças no Apoio'),
        ),
        migrations.RunSQL("""
            insert into tasks_reasonchoice(id, type, description)
            values (1, 'p', 'Pessoal'), (2, 't', 'Trânsito'), (3, 'c', 'Clima'), (4, 'a', 'Automático'), (5, 'o', 'Outros');
        """)
    ]
