# Generated by Django 3.2.5 on 2022-07-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_auto_20220602_1507'),
        ('tasks', '0038_task_supporting_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasonchoice',
            name='type',
            field=models.CharField(max_length=1, verbose_name='Motivos'),
        ),
        migrations.AlterField(
            model_name='task',
            name='advance_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='motivation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('d', 'day'), ('w', 'week'), ('m', 'month')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.submission'),
        ),
        migrations.AlterField(
            model_name='task',
            name='suggested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='supporting_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
