# Generated by Django 3.2.5 on 2022-07-16 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0027_auto_20220527_0933'),
        ('tasks', '0039_auto_20220715_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='periodicrelation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='supporting_changed',
        ),
        migrations.AlterField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usertask'),
        ),
        migrations.AlterField(
            model_name='group',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='periodicrelation',
            name='obs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='periodicrelation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='periodicrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.reasonchoice'),
        ),
        migrations.AlterField(
            model_name='reasonchoice',
            name='description',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='reasonchoice',
            name='type',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='response',
            name='file',
            field=models.FileField(null=True, upload_to=tasks.models.get_upload),
        ),
        migrations.AlterField(
            model_name='response',
            name='is_image',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='user_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usertask'),
        ),
        migrations.AlterField(
            model_name='seencomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.comment'),
        ),
        migrations.AlterField(
            model_name='seencomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='max_objects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='min_objects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('f', 'file'), ('t', 'text'), ('s', 'simple')], max_length=1),
        ),
        migrations.AlterField(
            model_name='supporting',
            name='data',
            field=models.FileField(null=True, upload_to=tasks.models.get_upload_supporting),
        ),
        migrations.AlterField(
            model_name='supporting',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='supporting',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='supporting',
            name='type',
            field=models.CharField(choices=[('f', 'file'), ('l', 'link'), ('v', 'video'), ('i', 'internal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='concluded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='concluded_by_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='is_concluded',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='obs',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='title_extension',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
