# Generated by Django 3.2.5 on 2022-07-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_task_is_editable'),
        ('tasks', '0040_auto_20220716_1520'),
    ]

    operations = [
    ]
