# Generated by Django 3.2.5 on 2022-10-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_alter_task_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodicrelation',
            unique_together=set(),
        ),
    ]
