# Generated by Django 3.2.5 on 2022-12-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_alter_periodicrelation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
