# Generated by Django 3.2.5 on 2023-04-11 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0044_alter_usertask_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='concluded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_task_concluded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
